Use matrix-free to apply boundary condition
adamantine-sim/adamantine pull request #204
Opened 2022-11-17 15:54 UTC by Rombur

This is a pretty big PR that does the following:
 - compute the boundary in a matrix-free way and remove unnecessary functions/variable.
 - fix a bug introduced by #201. Before that PR, adding material would not require load balancing because the number of cells was unchanged. After that PR, we perform load balancing because the number of dofs has changed. This means that the state ratios can be moved around.
 - update the tests. Some tests needed to be updated because we compute the boundary condition in a slightly different ways. The gold test needed to be redone.

Part of #172

2022-12-05 16:08 UTC, stvdwtt commented
@Rombur, is this still a draft, should I review it?

2022-12-05 16:21 UTC, Rombur commented
It's still a draft

2022-12-06 20:37 UTC, Rombur commented
This is ready for review

2022-12-08 17:22 UTC, stvdwtt requested changes

2022-12-08 17:22 UTC, stvdwtt commented on source/ThermalOperator.cc
> +          // We get one cells associated with the face
Typo?

```suggestion
          // We get one cell associated with the face
```

2022-12-08 17:22 UTC, stvdwtt commented on source/ThermalOperator.hh
> +   * face_local apply which is const.
Typo:

```suggestion
   * face_local_apply which is const.
```

2022-12-08 17:22 UTC, stvdwtt commented on source/ThermalOperator.cc
> +  // one of the two cells is using FE_Q
Any changes would be out of the scope of this PR, but I want to understand if this is worth looking at further.

Would you expect slow on the GPU with all these selection statements? Would there be any possibility of pre-calculating interface indices whenever the mesh changes and just loop through those? Or is that not possible for deal.II reasons? I'm not trying to prematurely optimize, but if there's the potential for an alternate way it'd be worth adding a note/issue.

2022-12-08 17:22 UTC, stvdwtt commented on source/ThermalPhysics.templates.hh
> +  _q_collection.push_back(QuadratureType(fe_degree + 1));
This is the `FENothing` quadrature? Do they need to have the same `QuadratureType` for the face calculations to work?

2022-12-08 17:22 UTC, stvdwtt commented on source/ThermalPhysics.templates.hh
> +  // of deposition (cosine and sine), and state rate.
"...and state rate."
Typo? Numer of states?

2022-12-08 19:32 UTC, Rombur commented on source/ThermalOperator.cc
> +  // one of the two cells is using FE_Q
First, right now we cannot loop over the faces on the GPU, it only works on the CPU. I still need to add that capability to deal.II. The way `FE_Nothing` is treated is very different on the CPU and the GPU. On the CPU, there is a lot more support for hp. On the GPU side, there is no support for hp but you can loop over a subdomain using a predicate. When looping on the face, what we are actually doing here is to use the DG infrastructure. That's why we loop over every face in the domain. For the GPU version, I will once again a predicate and so the filtering will be done during setup.

2022-12-08 19:32 UTC, Rombur commented on source/ThermalOperator.cc
> +      //  }
Yes, I was using it for debugging

2022-12-08 19:32 UTC, Rombur commented on source/ThermalPhysics.templates.hh
> +  _q_collection.push_back(QuadratureType(fe_degree + 1));
yes unfortunately. The DG matrix-free framework does not fully support hp

2022-12-08 19:32 UTC, Rombur commented on source/ThermalPhysics.templates.hh
> +  // of deposition (cosine and sine), and state rate.
state ratio.

2022-12-08 20:21 UTC, stvdwtt commented on source/ThermalOperator.cc
> +  // one of the two cells is using FE_Q
Ah, ok. Thanks!

2022-12-13 19:43 UTC, stvdwtt approved these changes
This looks good to me, as soon as the CUDA test passes I'll merge it in.

2022-12-13 21:41 UTC, Rombur commented
The CUDA test failed because the driver on the machine the CI was running is too old.  I have restarted the CI (see [here](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/320/pipeline))

2022-12-13 21:53 UTC, stvdwtt commented
Oh good, I was wondering how so many of the tests failed. Merging it in now.

2022-12-13 21:53 UTC, merged