Avoid compiler warnings
adamantine-sim/adamantine pull request #287
Opened 2024-05-20 19:31 UTC by masterleinad

While working on #282, I noticed that there are more warnings which this pull request fixes. I wasn't sure if we wanted to enforce this with `-Werror` or similar.

2024-05-23 15:22 UTC, stvdwtt approved these changes
These look good to me. @Rombur, any concerns?

2024-05-24 14:18 UTC, Rombur requested changes

2024-05-24 14:18 UTC, Rombur commented on ci/Dockerfile
> +        -DKokkos_ENABLE_CUDA_CONSTEXPR=$CUDA \
Don't modify the Dockerfile. This will unsync the image with the Dockerfile.

2024-05-24 14:42 UTC, masterleinad commented on ci/Dockerfile
> +        -DKokkos_ENABLE_CUDA_CONSTEXPR=$CUDA \
OK. I'll remove but most of the warnings are related to setting this option.

2024-05-24 14:55 UTC, Rombur commented on ci/Dockerfile
> +        -DKokkos_ENABLE_CUDA_CONSTEXPR=$CUDA \
Then why are you setting this option if it creates a bunch of warnings?

2024-05-24 14:58 UTC, masterleinad commented on ci/Dockerfile
> +        -DKokkos_ENABLE_CUDA_CONSTEXPR=$CUDA \
It removes all warnings related to calling `constexpr` `host` functions. This is also what we are doing in the `deal.II` CI, see https://github.com/dealii/dealii/blob/3c3910b004cec9be552eb224ceba4bc6fecd47b6/.github/workflows/linux.yml#L335, and we check for this option to be set for an external standalone `Kokkos`, see https://github.com/dealii/dealii/blob/3c3910b004cec9be552eb224ceba4bc6fecd47b6/cmake/modules/FindDEAL_II_KOKKOS.cmake#L53.

2024-05-24 15:10 UTC, Rombur approved these changes

2024-05-24 17:51 UTC, merged